name: "EVM Unit Tests"
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  evm-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Nix
        uses: cachix/install-nix-action@v17
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
      
      - name: Install npm dependencies
        run: nix develop --command bash -c 'cd evm-intent-framework && npm install'
      
      - name: Run EVM tests
        run: nix develop --command bash -c 'cd evm-intent-framework && npm test'

